[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "aegis"
version = "0.1.0"
license = "Apache-2.0"
urls = { home-page = "https://fhe.primuslabs.xyz/docs/intro/" }
description = "Aegis is an open-source framework based on MLIR that simplifies the use of Fully Homomorphic Encryption (FHE)."
authors = [{ name = "Primus", email = "a@primus.com" }]
readme = "README.md"
dependencies = []
requires-python = ">=3.10"

[tool.setuptools.packages.find]
include = ["primus*"]

[tool.setuptools.package-data]
primus = ["lib/*.so*", "lib/*.dylib*", "bin/*"]
