add_subdirectory(CollectMetadata)
add_subdirectory(ArithToSecret)
add_subdirectory(FuncToSecret)
add_subdirectory(MemrefToSecret)
add_subdirectory(SecretToFhe)
add_subdirectory(FoldArithChain)
add_subdirectory(Batching)
add_subdirectory(InsertRelinearize)
add_subdirectory(FheToEmitc)
add_subdirectory(CastToEmitcStub)
add_subdirectory(InsertEmitcPreamble)
add_subdirectory(LweToRlwe)
add_subdirectory(Unroll)
add_subdirectory(UnrollAndMemOpt)
add_subdirectory(ExtractLoopBody)
add_subdirectory(GlobalMemrefReplace)
add_subdirectory(ExpandMemrefCopy)
add_subdirectory(ForwardInsertToExtract)
add_subdirectory(ForwardStoreToLoad)


